import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'es' | 'en' | 'pt';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('es');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && ['es', 'en', 'pt'].includes(savedLanguage)) {
      setLanguage(savedLanguage);
    }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
    
    // Update HTML lang attribute
    document.documentElement.lang = lang === 'pt' ? 'pt-BR' : lang;
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || translations['es'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

const translations: Record<Language, Record<string, string>> = {
  es: {
    // Navigation
    'nav.home': 'Inicio',
    'nav.about': 'Quiénes Somos',
    'nav.services': 'Servicios para Empresas',
    'nav.jobs': 'Empleo',
    'nav.talent_program': 'Programa TIC Talento',
    'nav.contact': 'Contacto',
    'nav.login': 'Iniciar Sesión',
    'nav.logout': 'Cerrar Sesión',
    'nav.talent_registration': 'Registro Talento',

    // Hero Section
    'hero.title': 'El Talento que Impulsa la Industria TIC',
    'hero.subtitle': 'Conectamos a los líderes del sector de Testeo, Inspección y Certificación (TIC) con el talento que necesitan para crecer. Le entregamos una shortlist en 7 días. Garantizado.',
    'hero.discover_services': 'Descubra Nuestros Servicios',
    'hero.contact_us': 'Contáctanos',

    // Promise Section
    'promise.title': 'Contratación Estratégica, Sin Riesgos',
    'promise.shortlist.title': 'Shortlist en 7 Días',
    'promise.shortlist.desc': 'Nuestra base de datos de talento pre-evaluado nos permite actuar con una agilidad que nadie más puede ofrecer.',
    'promise.guarantee.title': 'Garantía de 90 Días',
    'promise.guarantee.desc': 'Si el candidato no cumple las expectativas en sus primeros tres meses, buscamos un reemplazo sin costo alguno.',
    'promise.zero_risk.title': 'Riesgo Cero',
    'promise.zero_risk.desc': 'Usted solo invierte cuando ha decidido contratar a uno de nuestros candidatos. Sin anticipos ni costos ocultos.',

    // Why Choose Us
    'why.title': 'Nacimos de la Industria para Servir a la Industria',
    'why.experience.title': '+30 Años de Experiencia Combinada',
    'why.experience.desc': 'Nuestro equipo entiende las necesidades específicas del sector TIC porque proviene de él.',
    'why.talent.title': '+15,000 Talentos en LATAM',
    'why.talent.desc': 'Una red activa y en constante expansión de profesionales especializados en la región.',
    'why.approach.title': 'Enfoque 360°',
    'why.approach.desc': 'Desde auditores especializados hasta directores regionales, cubrimos todos los niveles.',
    'why.ready.title': '¿Listo para Comenzar?',
    'why.ready.desc': 'Elige la forma que prefieras para contactarnos',
    'why.contact_form': 'Formulario de Contacto',
    'why.whatsapp': 'WhatsApp',
    'why.direct_email': 'Email Directo',

    // Services
    'services.title': 'Nuestros Servicios',
    'services.executive_search.title': 'Selección y Búsqueda de Ejecutivos',
    'services.executive_search.desc': 'Su terna de candidatos en 7 días. Talento especializado en TIC con metodología probada y garantía de resultados.',
    'services.hr_consulting.title': 'Consultoría en Recursos Humanos',
    'services.hr_consulting.desc': 'Fortalezca las bases de su organización con estrategias de retención y desarrollo de talento.',
    'services.coaching.title': 'Desarrollo & Coaching',
    'services.coaching.desc': 'Potenciamos las habilidades de sus equipos con programas de desarrollo personalizados y coaching ejecutivo.',
    'services.see_more': 'Ver Más',

    // Contact Page
    'contact.title': 'Contacto',
    'contact.subtitle': '¿Listo para encontrar el talento que su empresa necesita? Hablemos sobre cómo podemos ayudarle a alcanzar sus objetivos de contratación.',
    'contact.form.title': 'Envíanos un Mensaje',
    'contact.form.full_name': 'Nombre Completo',
    'contact.form.email': 'Correo Electrónico',
    'contact.form.company': 'Empresa',
    'contact.form.phone': 'Teléfono',
    'contact.form.query_type': 'Tipo de Consulta',
    'contact.form.message': 'Mensaje',
    'contact.form.message_placeholder': 'Cuéntanos sobre tus necesidades de talento...',
    'contact.form.privacy_accept': 'Acepto el tratamiento de mis datos personales de acuerdo con la',
    'contact.form.privacy_policy': 'Política de Privacidad',
    'contact.form.send': 'Enviar Mensaje',
    'contact.form.sending': 'Enviando...',
    'contact.direct_title': 'O contáctanos directamente',
    'contact.info.title': 'Información de Contacto',
    'contact.info.email': 'Email',
    'contact.info.phone': 'Teléfono',
    'contact.info.hours': 'Horario de Atención',
    'contact.info.hours_desc': 'Lunes a Viernes, 9:00 - 18:00 (UTC-3)',
    'contact.why.title': '¿Por qué Contactarnos?',
    'contact.why.consultation': 'Consultoría gratuita sobre sus necesidades de talento',
    'contact.why.proposal': 'Propuesta personalizada en 24 horas',
    'contact.why.no_commitment': 'Sin compromisos ni costos ocultos',
    'contact.why.immediate_access': 'Acceso inmediato a nuestra red de talento',

    // Footer
    'footer.quick_links': 'Enlaces Rápidos',
    'footer.community': 'Comunidad',
    'footer.contact': 'Contacto',
    'footer.privacy_policy': 'Política de Privacidad',
    'footer.cookies_policy': 'Política de Cookies',
    'footer.all_rights': '© 2024 TIC SELECT. Todos los derechos reservados.',

    // Enterprise Services
    'services_page.title': 'Soluciones de Talento que Generan Resultados',
    'services_page.executive_search.title': 'Selección y Búsqueda de Ejecutivos: Su Terna de Candidatos en 7 Días',
    'services_page.executive_search.subtitle': 'Nuestro proceso está diseñado para una sola cosa: entregarle el talento correcto en tiempo récord y con total seguridad.',
    'services_page.process': 'Nuestro Proceso',
    'services_page.step1.title': 'Definición Estratégica',
    'services_page.step1.desc': 'Entendemos a fondo sus necesidades de negocio para definir el perfil ideal.',
    'services_page.step2.title': 'Búsqueda y Validación',
    'services_page.step2.desc': 'Activamos nuestra base de datos, realizamos tests técnicos y validamos referencias 360.',
    'services_page.step3.title': 'Presentación de Finalistas',
    'services_page.step3.desc': 'En 7 días hábiles, le presentamos una selección curada de los mejores perfiles.',
    'services_page.step4.title': 'Coordinación y Cierre',
    'services_page.step4.desc': 'Gestionamos todo el proceso de entrevistas hasta la contratación exitosa.',
    'services_page.guarantee.title': 'Garantía 90 Días',
    'services_page.guarantee.desc': 'Si el candidato no resulta, lo reemplazamos sin costo',
    'services_page.cta.title': 'Deja de perder meses buscando',
    'services_page.cta.subtitle': 'En TIC Select hacemos que tu contratación sea rápida, segura y garantizada',
    'services_page.cta.button': 'Quiero mi primer shortlist en 7 días',
    'services_page.hr_consulting.title': 'Consultoría en Recursos Humanos',
    'services_page.hr_consulting.desc': 'Fortalezca las bases de su organización con nuestras soluciones de consultoría estratégica.',
    'services_page.coaching.title': 'Desarrollo & Coaching',
    'services_page.coaching.desc': 'Potenciamos las habilidades de sus equipos para convertirlos en los líderes del mañana.',
    'services_page.talent_universe.title': 'Para Empresas: Nuestro Universo de Talento',
    'services_page.talent_universe.desc': 'Nuestro mayor diferenciador es nuestra base de datos de talento TIC, viva y en constante actualización. Este activo estratégico nos permite encontrar perfiles altamente calificados con una velocidad inigualable.',
    'services_page.promise': 'En 7 días hábiles te presentamos candidatos validados técnica y culturalmente',
    'services_page.benefit1': 'Especialistas TIC: Auditores, Inspectores, Comerciales, KAMs y Ejecutivos especializados en Testing, Inspección y Certificación',
    'services_page.benefit2': 'Validación 360°: Evaluación técnica completa y referencias verificadas',
    'services_page.benefit3': 'Apoyo integral: Acompañamiento en entrevistas, negociación y cierre',
    'services_page.benefit4': 'Sin riesgo: Pago contra contratación efectiva',
    'services_page.hr_retention.title': 'Estrategias de Retención de Talento',
    'services_page.hr_retention.desc': 'Diseñamos e implementamos planes para fidelizar a sus empleados clave y reducir la rotación.',
    'services_page.hr_climate.title': 'Diagnóstico de Clima Organizacional',
    'services_page.hr_climate.desc': 'Medimos y analizamos el ambiente laboral para identificar oportunidades de mejora y aumentar la productividad.',
    'services_page.hr_salary.title': 'Análisis Salarial y de Estructuras',
    'services_page.hr_salary.desc': 'Asegúrese de que sus compensaciones y organigramas sean competitivos en el mercado actual.',
    'services_page.coaching_skills.title': 'Habilidades Blandas y Liderazgo',
    'services_page.coaching_skills.desc': 'Programas de coaching ejecutivo y talleres grupales para desarrollar habilidades de comunicación, gestión y liderazgo efectivo.',
    'services_page.coaching_career.title': 'Planes de Carrera',
    'services_page.coaching_career.desc': 'Ayudamos a estructurar rutas de crecimiento claras y motivadoras que impulsen el desarrollo profesional dentro de su empresa.',

    // About Us
    'about.title': 'Nacimos de la Industria para Servir a la Industria',
    'about.subtitle': 'Expertos TIC',
    'about.experts.title': 'Red de Expertos con Experiencia Real',
    'about.experts.desc': 'Nuestro equipo suma más de 30 años de experiencia combinada. Este conocimiento profundo nos permite identificar no solo las habilidades técnicas, sino el ADN cultural que garantiza un match perfecto.',
    'about.talent_universe.title': 'Un Universo de Talento a su Alcance',
    'about.talent_universe.desc': 'Gestionamos una red propia y en constante expansión con más de 15,000 talentos especializados en LATAM. No empezamos de cero; activamos nuestra red para entregar resultados con una velocidad y precisión inigualables.',
    'about.approach.title': 'Enfoque 360°',
    'about.approach.desc': 'Desde un auditor especializado hasta un Director Regional, entendemos las necesidades de cada nivel organizacional.',
    'about.cta.title': '¿Listo para potenciar su equipo?',
    'about.cta.subtitle': 'Elige la forma que prefieras para contactarnos',

    // Jobs/Vacancies
    'jobs.title': 'Busco Empleo en TIC',
    'jobs.subtitle': 'Si vienes de la Industria TIC, te favorece registrarte con nosotros para estar en nuestra base de datos de talentos. Te mandaremos noticias sobre la industria y ofertas exclusivas.',
    'jobs.register_now': 'Registrarme Ahora',
    'jobs.why_register': '¿Por qué registrarse con TIC Select?',
    'jobs.benefit1.title': 'Base de Datos Especializada',
    'jobs.benefit1.desc': 'Forma parte de nuestra exclusiva base de datos de talento TIC, donde empresas líderes buscan perfiles como el tuyo.',
    'jobs.benefit2.title': 'Ofertas Exclusivas',
    'jobs.benefit2.desc': 'Recibe ofertas laborales antes que nadie, directamente relacionadas con tu perfil y experiencia.',
    'jobs.benefit3.title': 'Noticias de la Industria',
    'jobs.benefit3.desc': 'Mantente actualizado con las últimas tendencias, tecnologías y oportunidades del sector TIC.',
    'jobs.how_it_works': 'Cómo Funciona',
    'jobs.step1.title': 'Regístrate',
    'jobs.step1.desc': 'Completa tu perfil profesional con tu experiencia y habilidades TIC.',
    'jobs.step2.title': 'Validación',
    'jobs.step2.desc': 'Nuestro equipo valida tu perfil y lo incluye en nuestra base de datos.',
    'jobs.step3.title': 'Matching',
    'jobs.step3.desc': 'Te conectamos con oportunidades que se ajusten a tu perfil y objetivos.',
    'jobs.step4.title': 'Oportunidades',
    'jobs.step4.desc': 'Recibe ofertas laborales y noticias relevantes de la industria TIC.',
    'jobs.cta.title': 'Tu Próxima Oportunidad TIC Te Está Esperando',
    'jobs.cta.subtitle': 'No dejes que las mejores oportunidades pasen de largo. Únete a nuestra red de profesionales TIC y acelera tu carrera profesional.',
    'jobs.register_free': 'Registrarme Gratis',
    'jobs.more_info': 'Más Información',
    'jobs.network_advantages': 'Ventajas de Nuestra Red',
    'jobs.advantage1': 'Confidencialidad: Tu información permanece privada hasta que decidas postular.',
    'jobs.advantage2': 'Relevancia: Solo recibes ofertas que coinciden con tu perfil.',
    'jobs.advantage3': 'Actualización: Mantente al día con tendencias y salarios del mercado TIC.',
    'jobs.advantage4': 'Sin compromiso: Puedes desactivar las notificaciones cuando quieras.',
    'jobs.join_professionals': 'Únete a Cientos de Profesionales TIC',
    'jobs.join_community': 'Forma parte de una comunidad exclusiva de talentos TIC que ya están aprovechando las mejores oportunidades del mercado.',
    'jobs.start_now': 'Comenzar Ahora',

    // TIC Talent Program
    'program.title': 'Impulsando el futuro del sector TIC',
    'program.subtitle': 'El programa crea un puente real entre la academia y la industria, acercando a los jóvenes a proyectos concretos y preparando a las empresas con el talento que necesitan para crecer.',
    'program.join': 'Únete al Programa',
    'program.what_is.title': '¿Qué es TIC Talento?',
    'program.benefits_companies': 'Beneficios para las Empresas',
    'program.benefits_youth': 'Beneficios para los Jóvenes',

    // Profiles Section
    'profiles_covered.title': 'Perfiles que Cubrimos: Nuestra Doble Expertise',
    'profiles_covered.ict_specialized': 'Perfiles Especializados del Sector TIC',
    'profiles_covered.functional_corporate': 'Áreas Funcionales y Corporativas',
    'profiles_covered.strategic_industries': 'Industrias Estratégicas que Servimos',
    'profiles_covered.auditors': 'Auditores y Especialistas en Normas:',
    'profiles_covered.inspectors': 'Inspectores de Campo:',
    'profiles_covered.lab': 'Personal de Laboratorio:',
    'profiles_covered.engineering': 'Ingeniería, Calidad y HSE:',
    'profiles_covered.executive': 'Liderazgo Ejecutivo y Estrategia:',
    'profiles_covered.commercial': 'Comercial y Desarrollo de Negocios:',
    'profiles_covered.operations': 'Operaciones y Proyectos:',
    'profiles_covered.finance': 'Finanzas y Administración:',
    'profiles_covered.hr': 'Recursos Humanos y Talento:',
    'profiles_covered.tech': 'Tecnología, Innovación y Marketing:',

    // Development & Coaching
    'development.title': 'Desarrollo & Coaching',
    'development.subtitle': 'Potenciamos las habilidades de sus equipos con programas de desarrollo personalizados y coaching ejecutivo especializado en la industria TIC.',
    'development.executive_coaching': 'Coaching Ejecutivo',
    'development.programs': 'Programas de Desarrollo',
    'development.why_different': '¿Por qué nuestro enfoque es diferente?',
    'development.field_experience': 'Experiencia de campo: Nuestros coaches provienen de la industria TIC',
    'development.proven_methodology': 'Metodología probada: Casos de éxito en organizaciones similares',
    'development.continuous_monitoring': 'Seguimiento continuo: Acompañamiento durante todo el proceso',
    'development.measurable_roi': 'ROI medible: Métricas claras de progreso y resultados',
    'development.free_consultation': '🚀 Consulta gratuita sobre desarrollo',
  },

  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About Us',
    'nav.services': 'Enterprise Services',
    'nav.jobs': 'Jobs',
    'nav.talent_program': 'TIC Talent Program',
    'nav.contact': 'Contact',
    'nav.login': 'Sign In',
    'nav.logout': 'Sign Out',
    'nav.talent_registration': 'Talent Registration',

    // Hero Section
    'hero.title': 'The Talent that Drives the TIC Industry',
    'hero.subtitle': 'We connect leaders in the Testing, Inspection and Certification (TIC) sector with the talent they need to grow. We deliver a shortlist in 7 days. Guaranteed.',
    'hero.discover_services': 'Discover Our Services',
    'hero.contact_us': 'Contact Us',

    // Promise Section
    'promise.title': 'Strategic Hiring, Risk-Free',
    'promise.shortlist.title': 'Shortlist in 7 Days',
    'promise.shortlist.desc': 'Our pre-evaluated talent database allows us to act with agility that no one else can offer.',
    'promise.guarantee.title': '90-Day Guarantee',
    'promise.guarantee.desc': 'If the candidate does not meet expectations in their first three months, we find a replacement at no cost.',
    'promise.zero_risk.title': 'Zero Risk',
    'promise.zero_risk.desc': 'You only invest when you have decided to hire one of our candidates. No advance payments or hidden costs.',

    // Why Choose Us
    'why.title': 'Born from the Industry to Serve the Industry',
    'why.experience.title': '+30 Years of Combined Experience',
    'why.experience.desc': 'Our team understands the specific needs of the TIC sector because it comes from it.',
    'why.talent.title': '+15,000 Talents in LATAM',
    'why.talent.desc': 'An active and constantly expanding network of specialized professionals in the region.',
    'why.approach.title': '360° Approach',
    'why.approach.desc': 'From specialized auditors to regional directors, we cover all levels.',
    'why.ready.title': 'Ready to Get Started?',
    'why.ready.desc': 'Choose your preferred way to contact us',
    'why.contact_form': 'Contact Form',
    'why.whatsapp': 'WhatsApp',
    'why.direct_email': 'Direct Email',

    // Services
    'services.title': 'Our Services',
    'services.executive_search.title': 'Executive Search & Selection',
    'services.executive_search.desc': 'Your candidate shortlist in 7 days. TIC specialized talent with proven methodology and guaranteed results.',
    'services.hr_consulting.title': 'Human Resources Consulting',
    'services.hr_consulting.desc': 'Strengthen your organization\'s foundations with talent retention and development strategies.',
    'services.coaching.title': 'Development & Coaching',
    'services.coaching.desc': 'We enhance your teams\' skills with personalized development programs and executive coaching.',
    'services.see_more': 'Learn More',

    // Contact Page
    'contact.title': 'Contact',
    'contact.subtitle': 'Ready to find the talent your company needs? Let\'s talk about how we can help you achieve your hiring goals.',
    'contact.form.title': 'Send Us a Message',
    'contact.form.full_name': 'Full Name',
    'contact.form.email': 'Email Address',
    'contact.form.company': 'Company',
    'contact.form.phone': 'Phone',
    'contact.form.query_type': 'Query Type',
    'contact.form.message': 'Message',
    'contact.form.message_placeholder': 'Tell us about your talent needs...',
    'contact.form.privacy_accept': 'I accept the processing of my personal data in accordance with the',
    'contact.form.privacy_policy': 'Privacy Policy',
    'contact.form.send': 'Send Message',
    'contact.form.sending': 'Sending...',
    'contact.direct_title': 'Or contact us directly',
    'contact.info.title': 'Contact Information',
    'contact.info.email': 'Email',
    'contact.info.phone': 'Phone',
    'contact.info.hours': 'Business Hours',
    'contact.info.hours_desc': 'Monday to Friday, 9:00 AM - 6:00 PM (UTC-3)',
    'contact.why.title': 'Why Contact Us?',
    'contact.why.consultation': 'Free consultation about your talent needs',
    'contact.why.proposal': 'Personalized proposal within 24 hours',
    'contact.why.no_commitment': 'No commitments or hidden costs',
    'contact.why.immediate_access': 'Immediate access to our talent network',

    // Footer
    'footer.quick_links': 'Quick Links',
    'footer.community': 'Community',
    'footer.contact': 'Contact',
    'footer.privacy_policy': 'Privacy Policy',
    'footer.cookies_policy': 'Cookie Policy',
    'footer.all_rights': '© 2024 TIC SELECT. All rights reserved.',

    // Enterprise Services
    'services_page.title': 'Talent Solutions that Generate Results',
    'services_page.executive_search.title': 'Executive Search & Selection: Your Candidate Shortlist in 7 Days',
    'services_page.executive_search.subtitle': 'Our process is designed for one thing: delivering the right talent in record time with total security.',
    'services_page.process': 'Our Process',
    'services_page.step1.title': 'Strategic Definition',
    'services_page.step1.desc': 'We thoroughly understand your business needs to define the ideal profile.',
    'services_page.step2.title': 'Search and Validation',
    'services_page.step2.desc': 'We activate our database, conduct technical tests and validate 360° references.',
    'services_page.step3.title': 'Finalist Presentation',
    'services_page.step3.desc': 'In 7 business days, we present you with a curated selection of the best profiles.',
    'services_page.step4.title': 'Coordination and Closing',
    'services_page.step4.desc': 'We manage the entire interview process until successful hiring.',
    'services_page.guarantee.title': '90-Day Guarantee',
    'services_page.guarantee.desc': 'If the candidate doesn\'t work out, we replace them at no cost',
    'services_page.cta.title': 'Stop wasting months searching',
    'services_page.cta.subtitle': 'At TIC Select we make your hiring fast, safe and guaranteed',
    'services_page.cta.button': 'I want my first shortlist in 7 days',
    'services_page.hr_consulting.title': 'Human Resources Consulting',
    'services_page.hr_consulting.desc': 'Strengthen your organization\'s foundations with our strategic consulting solutions.',
    'services_page.coaching.title': 'Development & Coaching',
    'services_page.coaching.desc': 'We enhance your teams\' skills to turn them into tomorrow\'s leaders.',
    'services_page.talent_universe.title': 'For Companies: Our Talent Universe',
    'services_page.talent_universe.desc': 'Our biggest differentiator is our TIC talent database, alive and constantly updated. This strategic asset allows us to find highly qualified profiles with unmatched speed.',
    'services_page.promise': 'In 7 business days we present you with technically and culturally validated candidates',
    'services_page.benefit1': 'TIC Specialists: Auditors, Inspectors, Sales, KAMs and Executives specialized in Testing, Inspection and Certification',
    'services_page.benefit2': '360° Validation: Complete technical evaluation and verified references',
    'services_page.benefit3': 'Comprehensive support: Assistance in interviews, negotiation and closing',
    'services_page.benefit4': 'No risk: Payment upon effective hiring',
    'services_page.hr_retention.title': 'Talent Retention Strategies',
    'services_page.hr_retention.desc': 'We design and implement plans to retain your key employees and reduce turnover.',
    'services_page.hr_climate.title': 'Organizational Climate Diagnosis',
    'services_page.hr_climate.desc': 'We measure and analyze the work environment to identify improvement opportunities and increase productivity.',
    'services_page.hr_salary.title': 'Salary and Structure Analysis',
    'services_page.hr_salary.desc': 'Ensure that your compensation and organizational charts are competitive in the current market.',
    'services_page.coaching_skills.title': 'Soft Skills and Leadership',
    'services_page.coaching_skills.desc': 'Executive coaching programs and group workshops to develop communication, management and effective leadership skills.',
    'services_page.coaching_career.title': 'Career Plans',
    'services_page.coaching_career.desc': 'We help structure clear and motivating growth paths that drive professional development within your company.',

    // About Us
    'about.title': 'Born from the Industry to Serve the Industry',
    'about.subtitle': 'TIC Experts',
    'about.experts.title': 'Network of Experts with Real Experience',
    'about.experts.desc': 'Our team has more than 30 years of combined experience. This deep knowledge allows us to identify not only technical skills, but the cultural DNA that guarantees a perfect match.',
    'about.talent_universe.title': 'A Universe of Talent at Your Reach',
    'about.talent_universe.desc': 'We manage our own constantly expanding network with more than 15,000 specialized talents in LATAM. We don\'t start from scratch; we activate our network to deliver results with unmatched speed and precision.',
    'about.approach.title': '360° Approach',
    'about.approach.desc': 'From a specialized auditor to a Regional Director, we understand the needs of each organizational level.',
    'about.cta.title': 'Ready to enhance your team?',
    'about.cta.subtitle': 'Choose your preferred way to contact us',

    // Jobs/Vacancies
    'jobs.title': 'Looking for TIC Jobs',
    'jobs.subtitle': 'If you come from the TIC Industry, it benefits you to register with us to be in our talent database. We will send you industry news and exclusive offers.',
    'jobs.register_now': 'Register Now',
    'jobs.why_register': 'Why register with TIC Select?',
    'jobs.benefit1.title': 'Specialized Database',
    'jobs.benefit1.desc': 'Be part of our exclusive TIC talent database, where leading companies look for profiles like yours.',
    'jobs.benefit2.title': 'Exclusive Offers',
    'jobs.benefit2.desc': 'Receive job offers before anyone else, directly related to your profile and experience.',
    'jobs.benefit3.title': 'Industry News',
    'jobs.benefit3.desc': 'Stay updated with the latest trends, technologies and opportunities in the TIC sector.',
    'jobs.how_it_works': 'How It Works',
    'jobs.step1.title': 'Register',
    'jobs.step1.desc': 'Complete your professional profile with your TIC experience and skills.',
    'jobs.step2.title': 'Validation',
    'jobs.step2.desc': 'Our team validates your profile and includes it in our database.',
    'jobs.step3.title': 'Matching',
    'jobs.step3.desc': 'We connect you with opportunities that fit your profile and goals.',
    'jobs.step4.title': 'Opportunities',
    'jobs.step4.desc': 'Receive job offers and relevant news from the TIC industry.',
    'jobs.cta.title': 'Your Next TIC Opportunity is Waiting',
    'jobs.cta.subtitle': 'Don\'t let the best opportunities pass you by. Join our network of TIC professionals and accelerate your career.',
    'jobs.register_free': 'Register Free',
    'jobs.more_info': 'More Information',
    'jobs.network_advantages': 'Advantages of Our Network',
    'jobs.advantage1': 'Confidentiality: Your information remains private until you decide to apply.',
    'jobs.advantage2': 'Relevance: You only receive offers that match your profile.',
    'jobs.advantage3': 'Updates: Stay up to date with TIC market trends and salaries.',
    'jobs.advantage4': 'No commitment: You can disable notifications whenever you want.',
    'jobs.join_professionals': 'Join Hundreds of TIC Professionals',
    'jobs.join_community': 'Be part of an exclusive community of TIC talents who are already taking advantage of the best market opportunities.',
    'jobs.start_now': 'Start Now',

    // TIC Talent Program
    'program.title': 'Driving the future of the TIC sector',
    'program.subtitle': 'The program creates a real bridge between academia and industry, bringing young people closer to concrete projects and preparing companies with the talent they need to grow.',
    'program.join': 'Join the Program',
    'program.what_is.title': 'What is TIC Talent?',
    'program.benefits_companies': 'Benefits for Companies',
    'program.benefits_youth': 'Benefits for Youth',

    // Profiles Section
    'profiles_covered.title': 'Profiles We Cover: Our Double Expertise',
    'profiles_covered.ict_specialized': 'Specialized ICT Sector Profiles',
    'profiles_covered.functional_corporate': 'Functional and Corporate Areas',
    'profiles_covered.strategic_industries': 'Strategic Industries We Serve',
    'profiles_covered.auditors': 'Auditors and Standards Specialists:',
    'profiles_covered.inspectors': 'Field Inspectors:',
    'profiles_covered.lab': 'Laboratory Personnel:',
    'profiles_covered.engineering': 'Engineering, Quality and HSE:',
    'profiles_covered.executive': 'Executive Leadership and Strategy:',
    'profiles_covered.commercial': 'Commercial and Business Development:',
    'profiles_covered.operations': 'Operations and Projects:',
    'profiles_covered.finance': 'Finance and Administration:',
    'profiles_covered.hr': 'Human Resources and Talent:',
    'profiles_covered.tech': 'Technology, Innovation and Marketing:',

    // Development & Coaching
    'development.title': 'Development & Coaching',
    'development.subtitle': 'We enhance your teams\' skills with personalized development programs and executive coaching specialized in the ICT industry.',
    'development.executive_coaching': 'Executive Coaching',
    'development.programs': 'Development Programs',
    'development.why_different': 'Why is our approach different?',
    'development.field_experience': 'Field experience: Our coaches come from the ICT industry',
    'development.proven_methodology': 'Proven methodology: Success stories in similar organizations',
    'development.continuous_monitoring': 'Continuous monitoring: Support throughout the entire process',
    'development.measurable_roi': 'Measurable ROI: Clear metrics of progress and results',
    'development.free_consultation': '🚀 Free development consultation',
  },

  pt: {
    // Navigation
    'nav.home': 'Início',
    'nav.about': 'Quem Somos',
    'nav.services': 'Serviços Empresariais',
    'nav.jobs': 'Empregos',
    'nav.talent_program': 'Programa TIC Talento',
    'nav.contact': 'Contato',
    'nav.login': 'Entrar',
    'nav.logout': 'Sair',
    'nav.talent_registration': 'Registro de Talento',

    // Hero Section
    'hero.title': 'O Talento que Impulsiona a Indústria TIC',
    'hero.subtitle': 'Conectamos líderes do setor de Testes, Inspeção e Certificação (TIC) com o talento necessário para crescer. Entregamos uma lista de candidatos em 7 dias. Garantido.',
    'hero.discover_services': 'Descubra Nossos Serviços',
    'hero.contact_us': 'Entre em Contato',

    // Promise Section
    'promise.title': 'Contratação Estratégica, Sem Riscos',
    'promise.shortlist.title': 'Lista de Candidatos em 7 Dias',
    'promise.shortlist.desc': 'Nossa base de dados de talentos pré-avaliados nos permite agir com agilidade que ninguém mais pode oferecer.',
    'promise.guarantee.title': 'Garantia de 90 Dias',
    'promise.guarantee.desc': 'Se o candidato não atender às expectativas nos primeiros três meses, buscamos um substituto sem custo algum.',
    'promise.zero_risk.title': 'Risco Zero',
    'promise.zero_risk.desc': 'Você só investe quando decidiu contratar um de nossos candidatos. Sem pagamentos antecipados ou custos ocultos.',

    // Why Choose Us
    'why.title': 'Nascemos da Indústria para Servir a Indústria',
    'why.experience.title': '+30 Anos de Experiência Combinada',
    'why.experience.desc': 'Nossa equipe entende as necessidades específicas do setor TIC porque vem dele.',
    'why.talent.title': '+15.000 Talentos na LATAM',
    'why.talent.desc': 'Uma rede ativa e em constante expansão de profissionais especializados na região.',
    'why.approach.title': 'Abordagem 360°',
    'why.approach.desc': 'De auditores especializados a diretores regionais, cobrimos todos os níveis.',
    'why.ready.title': 'Pronto para Começar?',
    'why.ready.desc': 'Escolha sua forma preferida de nos contatar',
    'why.contact_form': 'Formulário de Contato',
    'why.whatsapp': 'WhatsApp',
    'why.direct_email': 'Email Direto',

    // Services
    'services.title': 'Nossos Serviços',
    'services.executive_search.title': 'Seleção e Busca Executiva',
    'services.executive_search.desc': 'Sua lista de candidatos em 7 dias. Talento especializado em TIC com metodologia comprovada e resultados garantidos.',
    'services.hr_consulting.title': 'Consultoria em Recursos Humanos',
    'services.hr_consulting.desc': 'Fortaleça as bases de sua organização com estratégias de retenção e desenvolvimento de talentos.',
    'services.coaching.title': 'Desenvolvimento & Coaching',
    'services.coaching.desc': 'Potencializamos as habilidades de suas equipes com programas de desenvolvimento personalizados e coaching executivo.',
    'services.see_more': 'Saiba Mais',

    // Contact Page
    'contact.title': 'Contato',
    'contact.subtitle': 'Pronto para encontrar o talento que sua empresa precisa? Vamos conversar sobre como podemos ajudá-lo a alcançar seus objetivos de contratação.',
    'contact.form.title': 'Envie-nos uma Mensagem',
    'contact.form.full_name': 'Nome Completo',
    'contact.form.email': 'Endereço de Email',
    'contact.form.company': 'Empresa',
    'contact.form.phone': 'Telefone',
    'contact.form.query_type': 'Tipo de Consulta',
    'contact.form.message': 'Mensagem',
    'contact.form.message_placeholder': 'Conte-nos sobre suas necessidades de talento...',
    'contact.form.privacy_accept': 'Aceito o processamento de meus dados pessoais de acordo com a',
    'contact.form.privacy_policy': 'Política de Privacidade',
    'contact.form.send': 'Enviar Mensagem',
    'contact.form.sending': 'Enviando...',
    'contact.direct_title': 'Ou entre em contato diretamente',
    'contact.info.title': 'Informações de Contato',
    'contact.info.email': 'Email',
    'contact.info.phone': 'Telefone',
    'contact.info.hours': 'Horário de Atendimento',
    'contact.info.hours_desc': 'Segunda a Sexta, 9:00 - 18:00 (UTC-3)',
    'contact.why.title': 'Por que nos Contatar?',
    'contact.why.consultation': 'Consultoria gratuita sobre suas necessidades de talento',
    'contact.why.proposal': 'Proposta personalizada em 24 horas',
    'contact.why.no_commitment': 'Sem compromissos ou custos ocultos',
    'contact.why.immediate_access': 'Acesso imediato à nossa rede de talentos',

    // Footer
    'footer.quick_links': 'Links Rápidos',
    'footer.community': 'Comunidade',
    'footer.contact': 'Contato',
    'footer.privacy_policy': 'Política de Privacidade',
    'footer.cookies_policy': 'Política de Cookies',
    'footer.all_rights': '© 2024 TIC SELECT. Todos os direitos reservados.',

    // Enterprise Services
    'services_page.title': 'Soluções de Talento que Geram Resultados',
    'services_page.executive_search.title': 'Seleção e Busca Executiva: Sua Lista de Candidatos em 7 Dias',
    'services_page.executive_search.subtitle': 'Nosso processo é projetado para uma coisa: entregar o talento certo em tempo recorde com total segurança.',
    'services_page.process': 'Nosso Processo',
    'services_page.step1.title': 'Definição Estratégica',
    'services_page.step1.desc': 'Entendemos profundamente suas necessidades de negócio para definir o perfil ideal.',
    'services_page.step2.title': 'Busca e Validação',
    'services_page.step2.desc': 'Ativamos nossa base de dados, realizamos testes técnicos e validamos referências 360°.',
    'services_page.step3.title': 'Apresentação de Finalistas',
    'services_page.step3.desc': 'Em 7 dias úteis, apresentamos uma seleção curada dos melhores perfis.',
    'services_page.step4.title': 'Coordenação e Fechamento',
    'services_page.step4.desc': 'Gerenciamos todo o processo de entrevistas até a contratação bem-sucedida.',
    'services_page.guarantee.title': 'Garantia de 90 Dias',
    'services_page.guarantee.desc': 'Se o candidato não der certo, substituímos sem custo',
    'services_page.cta.title': 'Pare de perder meses procurando',
    'services_page.cta.subtitle': 'Na TIC Select tornamos sua contratação rápida, segura e garantida',
    'services_page.cta.button': 'Quero minha primeira lista em 7 dias',
    'services_page.hr_consulting.title': 'Consultoria em Recursos Humanos',
    'services_page.hr_consulting.desc': 'Fortaleça as bases da sua organização com nossas soluções de consultoria estratégica.',
    'services_page.coaching.title': 'Desenvolvimento & Coaching',
    'services_page.coaching.desc': 'Potencializamos as habilidades de suas equipes para transformá-las nos líderes de amanhã.',
    'services_page.talent_universe.title': 'Para Empresas: Nosso Universo de Talento',
    'services_page.talent_universe.desc': 'Nosso maior diferencial é nosso banco de dados de talentos TIC, vivo e em constante atualização. Este ativo estratégico nos permite encontrar perfis altamente qualificados com velocidade incomparável.',
    'services_page.promise': 'Em 7 dias úteis apresentamos candidatos validados técnica e culturalmente',
    'services_page.benefit1': 'Especialistas TIC: Auditores, Inspetores, Comerciais, KAMs e Executivos especializados em Testes, Inspeção e Certificação',
    'services_page.benefit2': 'Validação 360°: Avaliação técnica completa e referências verificadas',
    'services_page.benefit3': 'Apoio integral: Acompanhamento em entrevistas, negociação e fechamento',
    'services_page.benefit4': 'Sem risco: Pagamento mediante contratação efetiva',
    'services_page.hr_retention.title': 'Estratégias de Retenção de Talentos',
    'services_page.hr_retention.desc': 'Projetamos e implementamos planos para fidelizar seus funcionários-chave e reduzir a rotatividade.',
    'services_page.hr_climate.title': 'Diagnóstico de Clima Organizacional',
    'services_page.hr_climate.desc': 'Medimos e analisamos o ambiente de trabalho para identificar oportunidades de melhoria e aumentar a produtividade.',
    'services_page.hr_salary.title': 'Análise Salarial e de Estruturas',
    'services_page.hr_salary.desc': 'Certifique-se de que suas compensações e organogramas sejam competitivos no mercado atual.',
    'services_page.coaching_skills.title': 'Habilidades Interpessoais e Liderança',
    'services_page.coaching_skills.desc': 'Programas de coaching executivo e workshops em grupo para desenvolver habilidades de comunicação, gestão e liderança eficaz.',
    'services_page.coaching_career.title': 'Planos de Carreira',
    'services_page.coaching_career.desc': 'Ajudamos a estruturar caminhos de crescimento claros e motivadores que impulsionam o desenvolvimento profissional dentro da sua empresa.',

    // About Us
    'about.title': 'Nascemos da Indústria para Servir a Indústria',
    'about.subtitle': 'Especialistas TIC',
    'about.experts.title': 'Rede de Especialistas com Experiência Real',
    'about.experts.desc': 'Nossa equipe soma mais de 30 anos de experiência combinada. Este conhecimento profundo nos permite identificar não apenas as habilidades técnicas, mas o DNA cultural que garante um match perfeito.',
    'about.talent_universe.title': 'Um Universo de Talentos ao Seu Alcance',
    'about.talent_universe.desc': 'Gerenciamos uma rede própria em constante expansão com mais de 15.000 talentos especializados na LATAM. Não começamos do zero; ativamos nossa rede para entregar resultados com velocidade e precisão incomparáveis.',
    'about.approach.title': 'Abordagem 360°',
    'about.approach.desc': 'De um auditor especializado a um Diretor Regional, entendemos as necessidades de cada nível organizacional.',
    'about.cta.title': 'Pronto para potencializar sua equipe?',
    'about.cta.subtitle': 'Escolha sua forma preferida de nos contatar',

    // Jobs/Vacancies
    'jobs.title': 'Procuro Emprego em TIC',
    'jobs.subtitle': 'Se você vem da Indústria TIC, é vantajoso se registrar conosco para estar em nossa base de dados de talentos. Enviaremos notícias da indústria e ofertas exclusivas.',
    'jobs.register_now': 'Registrar Agora',
    'jobs.why_register': 'Por que se registrar com a TIC Select?',
    'jobs.benefit1.title': 'Base de Dados Especializada',
    'jobs.benefit1.desc': 'Faça parte de nossa base exclusiva de talentos TIC, onde empresas líderes procuram perfis como o seu.',
    'jobs.benefit2.title': 'Ofertas Exclusivas',
    'jobs.benefit2.desc': 'Receba ofertas de trabalho antes de qualquer um, diretamente relacionadas ao seu perfil e experiência.',
    'jobs.benefit3.title': 'Notícias da Indústria',
    'jobs.benefit3.desc': 'Mantenha-se atualizado com as últimas tendências, tecnologias e oportunidades do setor TIC.',
    'jobs.how_it_works': 'Como Funciona',
    'jobs.step1.title': 'Registre-se',
    'jobs.step1.desc': 'Complete seu perfil profissional com sua experiência e habilidades TIC.',
    'jobs.step2.title': 'Validação',
    'jobs.step2.desc': 'Nossa equipe valida seu perfil e o inclui em nossa base de dados.',
    'jobs.step3.title': 'Correspondência',
    'jobs.step3.desc': 'Conectamos você com oportunidades que se encaixam no seu perfil e objetivos.',
    'jobs.step4.title': 'Oportunidades',
    'jobs.step4.desc': 'Receba ofertas de trabalho e notícias relevantes da indústria TIC.',
    'jobs.cta.title': 'Sua Próxima Oportunidade TIC Está Esperando',
    'jobs.cta.subtitle': 'Não deixe as melhores oportunidades passarem. Junte-se à nossa rede de profissionais TIC e acelere sua carreira.',
    'jobs.register_free': 'Registrar Grátis',
    'jobs.more_info': 'Mais Informações',
    'jobs.network_advantages': 'Vantagens da Nossa Rede',
    'jobs.advantage1': 'Confidencialidade: Suas informações permanecem privadas até você decidir se candidatar.',
    'jobs.advantage2': 'Relevância: Você só recebe ofertas que correspondem ao seu perfil.',
    'jobs.advantage3': 'Atualização: Mantenha-se atualizado com tendências e salários do mercado TIC.',
    'jobs.advantage4': 'Sem compromisso: Você pode desativar notificações quando quiser.',
    'jobs.join_professionals': 'Junte-se a Centenas de Profissionais TIC',
    'jobs.join_community': 'Faça parte de uma comunidade exclusiva de talentos TIC que já estão aproveitando as melhores oportunidades do mercado.',
    'jobs.start_now': 'Começar Agora',

    // TIC Talent Program
    'program.title': 'Impulsionando o futuro do setor TIC',
    'program.subtitle': 'O programa cria uma ponte real entre a academia e a indústria, aproximando os jovens de projetos concretos e preparando as empresas com o talento que precisam para crescer.',
    'program.join': 'Junte-se ao Programa',
    'program.what_is.title': 'O que é TIC Talento?',
    'program.benefits_companies': 'Benefícios para as Empresas',
    'program.benefits_youth': 'Benefícios para os Jovens',

    // Profiles Section
    'profiles_covered.title': 'Perfis que Cobrimos: Nossa Dupla Expertise',
    'profiles_covered.ict_specialized': 'Perfis Especializados do Setor TIC',
    'profiles_covered.functional_corporate': 'Áreas Funcionais e Corporativas',
    'profiles_covered.strategic_industries': 'Indústrias Estratégicas que Atendemos',
    'profiles_covered.auditors': 'Auditores e Especialistas em Normas:',
    'profiles_covered.inspectors': 'Inspetores de Campo:',
    'profiles_covered.lab': 'Pessoal de Laboratório:',
    'profiles_covered.engineering': 'Engenharia, Qualidade e HSE:',
    'profiles_covered.executive': 'Liderança Executiva e Estratégia:',
    'profiles_covered.commercial': 'Comercial e Desenvolvimento de Negócios:',
    'profiles_covered.operations': 'Operações e Projetos:',
    'profiles_covered.finance': 'Finanças e Administração:',
    'profiles_covered.hr': 'Recursos Humanos e Talentos:',
    'profiles_covered.tech': 'Tecnologia, Inovação e Marketing:',

    // Development & Coaching
    'development.title': 'Desenvolvimento & Coaching',
    'development.subtitle': 'Potencializamos as habilidades de suas equipes com programas de desenvolvimento personalizados e coaching executivo especializado na indústria TIC.',
    'development.executive_coaching': 'Coaching Executivo',
    'development.programs': 'Programas de Desenvolvimento',
    'development.why_different': 'Por que nossa abordagem é diferente?',
    'development.field_experience': 'Experiência de campo: Nossos coaches vêm da indústria TIC',
    'development.proven_methodology': 'Metodologia comprovada: Casos de sucesso em organizações similares',
    'development.continuous_monitoring': 'Acompanhamento contínuo: Suporte durante todo o processo',
    'development.measurable_roi': 'ROI mensurável: Métricas claras de progresso e resultados',
    'development.free_consultation': '🚀 Consulta gratuita sobre desenvolvimento',
  },
};