// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://quklmmzdbefzyfbktkkb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF1a2xtbXpkYmVmenlmYmt0a2tiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1OTQ1MjEsImV4cCI6MjA3MjE3MDUyMX0.uvAnYJDETmpP3uqlxHwfIyfdVnQsMJ9xnDb_ymYnAMY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});